In [ ]:
# PANDAS -> 데이터 정제

In [ ]:
# NUMPY -> 수치데이터를 다루는 라이브러리 
#           ; 다차원 행렬 자료구조인 ndarray를 이용해 벡터 및 행렬을 사용하는 선형대수 계산에서 주로 사용

# numpy.zeros((a,b)) -> axb사이즈의 영행렬 생성
# numpy.ones((a,b)) -> axb사이즈의 모든 원소가 1인 행렬 생성
# numpy.eye(n) -> 단위행렬(행렬 a와 행렬곱을 했을 때 똑같이 행렬 a가 나오는 행렬) ; 대각선으로 1이 할당, 그 외 0 할당
# numpy.random.random((a,b)) -> a에서 b사이의 랜덤값 반환
# numpy.full() -> 행렬의 모든 값을 10으로 초기화
# numpy.arange() -> default) 0부터 n-1까지의 원소값을 가지는 배열 생성
# numpy.arange(i,j,k) -> i부터 j까지 k씩 증가하는 원소값을 가지는 배열 생성

# + -> add()    - -> subtract()    * -> multiply()     / -> divide()

# 행렬곱 -> @(;연산자) or dot()(함수)

In [ ]:
# Matplotlib -> 데이터 시각화(차트, 플롯)(; 파이 차트, 바 차트, 라인 플롯, Scatter)

# plot(x축리스트, y축리스트, 옵션...) -> matplotlib.pyplot 에 위치, 값들은 리스트로 입력, x는 자동으로 0,1,2,3...(default)로 지정됨
# xx_chart = matplotlib.pyplot.plot()
# xx_chart.show() 를 통해 차트를 실제로 그림

# pyplot.xlabel() or ylabel() -> 그래프의 x,y축에 대한 레이블 표시(각 축에 대한 이름 지정)
# pypot.~~() -> ㅌ,
# pyplot.legend() -> 그래프 라인의 범례 추가,
#                    매개변수로 loc="위치(upper center등과 같이 str 지정 or 코드 지정)" 지정 시 지정 위치에 범례 나타남


# pyplot.subplot(row,col,pos) -> 행의 수, 열의 수, 위치(어느 위치에 거칠지ㅒ)


In [1]:
!pip install pandas


In [2]:
import pandas as pd

In [3]:
pd_list = pd.Series([5000, 6000, 6500,6500], index=["아메리카노","카페라떼","카페모카","카푸치노"])


In [4]:
print(pd_list)

아메리카노    5000
카페라떼     6000
카페모카     6500
카푸치노     6500
dtype: int64


In [5]:
print("시리즈 형태의 데이터에서 index 값: ", pd_list.index)
print("시리즈 형태의 데이터에서 value 값: ", pd_list.values)

시리즈 형태의 데이터에서 index 값:  Index(['아메리카노', '카페라떼', '카페모카', '카푸치노'], dtype='object')
시리즈 형태의 데이터에서 value 값:  [5000 6000 6500 6500]


In [7]:
# 2차원 데이터셋 DataFrame = 여러 Series를 합한 것 ; 분리도 가능
# 데이터프레임 생성

_value = [[1,2,3],[4,5,6],[7,8,9]]
_index = ['a','b','c']
_column = ['A','B','C']

df = pd.DataFrame(data=_value, index=_index, columns=_column)
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [11]:
print("데이터프레임의 index 값: ", df.index)
print("데이터프레임의 column 값: ", df.columns)
print("데이터프레임의 value 값:\n", df.values)

데이터프레임의 index 값:  Index(['a', 'b', 'c'], dtype='object')
데이터프레임의 column 값:  Index(['A', 'B', 'C'], dtype='object')
데이터프레임의 value 값:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 딕셔너리 형태의 데이터를 이용해 데이터프레임 생성

_value = {
    "name":["test","test2","test3"],
    "age":[20,30,25],
    "phone":["01012345667","01022223333","01043215432"]
    }

print(_value)

{'name': ['test', 'test2', 'test3'], 'age': [20, 30, 25], 'phone': ['01012345667', '01022223333', '01043215432']}


In [14]:
# 딕셔너리의 키가 컬럼명이 됨
df2 = pd.DataFrame(_value)

df2

name  age        phone
0   test   20  01012345667
1  test2   30  01022223333
2  test3   25  01043215432

In [23]:
df2["age"]

0    20
1    30
2    25
Name: age, dtype: int64

In [24]:
df2.age

0    20
1    30
2    25
Name: age, dtype: int64

In [ ]:
## 경로
#1.절대경로 ; 환경이 바뀌어도 항상 같은 장소를 가리킴 -> full path
#2.상대경로 ; 환경에 따라 가리키는 장소가 달라짐 ->  ./ (현재위치)  ../(상위)   폴더명/(하위폴더)

In [25]:
# .csv .tsv -> comma(tab) seperated value
# .json -> [{"a":"b"},...]

In [28]:
# 코로나 데이터 로드
# 현재파일>csv>corona.csv

data=pd.read_csv("./csv/corona.csv")
# data=pd.read_csv("C:/Users/umjiwoo/OneDrive/문서/금융빅데이터 과정/ubion/csv/corona.csv")
data

Unnamed: 0                 createDt  deathCnt  decideCnt  seq   stateDt  \
0             0  2022-06-08 09:09:05.982     24305   18188200  904  20220608   
1             1  2022-06-07 09:09:00.897     24299   18174842  903  20220607   
2             2  2022-06-06 09:00:06.734     24279   18168670  902  20220606   
3             3  2022-06-05 08:53:19.426     24258   18163648  901  20220605   
4             4  2022-06-04 08:56:49.219     24238   18153814  900  20220604   
..          ...                      ...       ...        ...  ...       ...   
815         815  2020-03-14 00:00:00.000        72       8086   55  20200314   
816         816  2020-03-13 00:00:00.000        67       7979   54  20200313   
817         817  2020-03-12 00:00:00.000        66       7869   53  20200312   
818         818  2020-03-11 00:00:00.000        60       7755   52  20200311   
819         819  2020-03-10 00:00:00.000        54       7513   51  20200310   

    stateTime                 updateDt  accExamCnt  accDefRate  
0       00:00                      NaN         NaN         NaN  
1       00:00  2022-06-08 09:10:36.846         NaN         NaN  
2       00:00  2022-06-08 09:10:50.441         NaN         NaN  
3       00:00  2022-06-08 09:11:04.758         NaN         NaN  
4       00:00  2022-06-08 09:11:26.303         NaN         NaN  
..        ...                      ...         ...         ...  
815     00:00   2021-10-07 10:30:51.51    261335.0    3.318000  
816     00:00   2021-10-07 10:30:51.51    248647.0    3.458499  
817     00:00   2021-10-07 10:30:51.51    234998.0    3.621744  
818     00:00   2021-10-07 10:30:51.51    222395.0    3.804175  
819     00:00   2021-10-07 10:30:51.51    210144.0    3.919308  

[820 rows x 10 columns]

In [ ]:
data2=pd.read_csv("./csv/num_1/chipotle.tsv")
